services:
  nginx-dev:
    image: nginx:1.29.0-alpine
    networks:
      - traefik-net
      - web-network
    volumes:
      - ./:/var/www
      - ./docker/nginx/dev:/etc/nginx/conf.d/
    depends_on:
      - app-dev
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.ttt-api.rule=Host(`${APP_HOSTNAME:-ttt-api.dev.localhost}`)"
      - "traefik.http.services.ttt-api.loadbalancer.server.port=80"

  app-dev:
    build:
      context: ./docker/php/
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/var/www
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - db-network
      - web-network
    depends_on:
      mysql-dev:
        condition: service_healthy

  mysql-dev:
    image: mysql:9.3.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_EXTERNAL_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${DB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    networks:
      - db-network

networks:
  db-network:
  web-network:
  traefik-net:
    external: true
volumes:
  db-data:
